Introduce option to define timeout for time-consuming file operations
Open-CAS/test-framework pull request #17
Opened 2024-10-02 19:55 UTC by robertbaldyga

2024-10-02 19:55 UTC, pep8speaks commented
Hello @robertbaldyga! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test_utils/filesystem/file.py`](https://github.com/Open-CAS/test-framework/blob/00147eaf7c863f372c9c6f0cad51a70f46bea6fe/test_utils/filesystem/file.py):

> [Line 24:1](https://github.com/Open-CAS/test-framework/blob/00147eaf7c863f372c9c6f0cad51a70f46bea6fe/test_utils/filesystem/file.py#L24): [E101](https://duckduckgo.com/?q=pep8%20E101) indentation contains mixed spaces and tabs
> [Line 24:1](https://github.com/Open-CAS/test-framework/blob/00147eaf7c863f372c9c6f0cad51a70f46bea6fe/test_utils/filesystem/file.py#L24): [W191](https://duckduckgo.com/?q=pep8%20W191) indentation contains tabs

2024-10-03 05:18 UTC, mmichal10 approved these changes

2024-10-03 06:11 UTC, jfckm submitted a review, later dismissed

2024-10-03 06:30 UTC, mmichal10 requested changes

2024-10-03 06:30 UTC, mmichal10 commented on test_utils/filesystem/file.py
> +	return fs_utils.md5sum(str(self), binary)
You're using tab instead of spaces

2024-10-03 06:53 UTC, robertbaldyga commented on test_utils/filesystem/file.py
> +	return fs_utils.md5sum(str(self), binary)
Fixed.

2024-10-03 07:47 UTC, mmichal10 approved these changes

2024-10-03 07:52 UTC, merged