RAID API
Open-CAS/test-framework pull request #192
Opened 2020-08-10 10:49 UTC by Deixx

2020-08-10 10:49 UTC, pep8speaks commented
Hello @Deixx! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`storage_devices/raid.py`](https://github.com/Open-CAS/test-framework/blob/0c6df90b8c503f7e1ff51ad74a3320fe845cc110/storage_devices/raid.py):

> [Line 137:25](https://github.com/Open-CAS/test-framework/blob/0c6df90b8c503f7e1ff51ad74a3320fe845cc110/storage_devices/raid.py#L137): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

2020-08-11 07:06 UTC, robertbaldyga commented on test_tools/mdadm.py
> +    def assemble(devices: [Device] = None):
IMO low level tool wrappers shouldn't use higher level abstraction classes like `Device`. It creates interdependencies between components, while from design perspective one-way dependencies is preferred. Passing simple list of device paths should be enough in this case. The same applies to other methods.

2020-08-11 07:12 UTC, robertbaldyga commented on storage_devices/raid.py
> +        mdadm_scan = Mdadm.examine().stdout
Why this output is not parsed in `Mdadm`? It's responsible for interfacing with mdadm utility after all, so parsing output to more useful form seems to be right task for that class.

2020-08-11 07:17 UTC, robertbaldyga commented on storage_devices/raid.py
> +readlink_md_cmd = "readlink --canonicalize-existing /dev/md/"
We use readlink also in few other places, so maybe it already deserves its own utility wrapper.

2020-08-11 07:20 UTC, robertbaldyga commented on storage_devices/raid.py
> +        return uuid
This parsing also could be made inside `Mdadm` class.

2020-08-26 09:06 UTC, Ostrokrzew commented on test_tools/fs_utils.py
> +    ).stdout
Maybe move it to Symlink class (test_utils/filesystem/symlink.py)?

2020-08-28 13:50 UTC, Deixx commented on test_tools/fs_utils.py
> +    ).stdout
Symlink is a class designed to represent actual object, readlink is just a system utility

2020-09-01 14:47 UTC, Ostrokrzew requested changes

2020-09-01 14:47 UTC, Ostrokrzew commented on test_tools/mdadm.py
> +            cmd += f"--size={conf.size.get_value(Unit.KibiByte)} "
Please, cast this to int.

2020-09-01 17:05 UTC, robertbaldyga commented on storage_devices/raid.py
> +            raise CmdException(f"Failed to start RAID volume", raid_output)
We could raise this exception inside `Mdadm.create()` instead of returning exit code.

2020-09-01 17:05 UTC, robertbaldyga commented on storage_devices/raid.py
> +            Mdadm.stop(self.container_path)
Missing check for potential errors (btw `Mdadm.stop()` could also raise an exception).

2020-09-04 10:30 UTC, Ostrokrzew approved these changes

2020-09-04 17:52 UTC, robertbaldyga approved these changes

2020-09-04 17:52 UTC, merged