Increase rsync timeout and check if rsync ended successfully
Open-CAS/test-framework pull request #203
Opened 2020-08-18 13:13 UTC by katlapinka

Signed-off-by: Katarzyna Lapinska <katarzyna.lapinska@intel.com>

2020-08-19 08:53 UTC, Deixx requested changes

2020-08-19 08:53 UTC, Deixx commented on connection/ssh_executor.py
> +            TestRun.LOGGER.exception(f"Exception occurred during rsync process.n{e}")
I assume you wanted \n before {e}

2020-08-19 15:59 UTC, Ostrokrzew approved these changes

2020-08-24 11:38 UTC, Deixx approved these changes

2020-09-01 16:55 UTC, merged