Make timeout for power cycle same as for reboot
Open-CAS/test-framework pull request #212
Opened 2020-09-17 11:34 UTC by Ostrokrzew

Signed-off-by: Slawomir Jankowski <slawomir.jankowski@intel.com>

2020-10-05 15:40 UTC, robertbaldyga requested changes

2020-10-05 15:40 UTC, robertbaldyga commented on connection/base_executor.py
> +
Reboot is ability of `SshExecutor`. It should not be in the `BaseExecutor`.

2020-10-05 15:40 UTC, robertbaldyga commented on internal_plugins/power_control_libvirt/__init__.py
> +         if TestRun.executor.reboot_timeout is not None else TestRun.executor.wait_for_connection())
You can obtain reboot timeout value from `TestRun.config`. That way you don't need to access executor internals.

2020-10-07 19:34 UTC, robertbaldyga requested changes

2020-10-07 19:34 UTC, robertbaldyga commented on internal_plugins/power_control_libvirt/__init__.py
> +            TestRun.executor.wait_for_connection(timedelta(seconds=timeout))
```python
timedelta(seconds=int(timeout))
```
`timedelta` doesn't accept `str`

2020-10-12 07:39 UTC, Deixx approved these changes

2020-10-20 12:27 UTC, katlapinka approved these changes

2020-11-03 09:40 UTC, robertbaldyga approved these changes

2020-11-03 09:40 UTC, merged