fix for remove_partitions method
Open-CAS/test-framework pull request #218
Opened 2020-11-25 15:43 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowsky@gmail.com>

2020-11-26 07:04 UTC, katlapinka commented on test_tools/disk_utils.py
> +    TestRun.executor.run(f"sleep 1")
I'm just curious - why is this needed here? Did partitions unmounting process not finish before running dd?

2020-11-26 08:42 UTC, Deixx commented on test_tools/disk_utils.py
> +    TestRun.executor.run(f"sleep 1")
Short comment could be added (NOT the full explanation below ;))
We've run into a problem on one particular platform and only with HDD disks. Partitions would not disappear after dd was run and it looked like it was a race condition. `ls /dev/sdx -1` had displayed either the device and its partition (in that case partition would stay in the system), or only the device, but with error that partition cannot be accessed. I don't know how exactly ls works, but it looked like some initial scan "saw" the partition, but it was not there for the proper scan.  With trial and error we concluded that `mdadm --zero-superblock` was not releasing the device in time.
Actually maybe the sleep should be moved to the end of Mdadm.zero_superblock()... Removing partitions is quite common operation (opposed to zeroing raid metadata).

2020-11-26 08:42 UTC, Deixx requested changes
Move the sleep to Mdadm.zero_superbloct()

2020-12-02 14:15 UTC, robertbaldyga commented on test_tools/disk_utils.py
> +    TestRun.executor.run(f"sleep 1")
> With trial and error we concluded that mdadm --zero-superblock was not releasing the device in time.

Whoa, it looks like a bug in `mdadm`, doesn't it?

2020-12-11 15:52 UTC, closed without merging

2020-12-11 16:50 UTC, karolinavelkaja commented
Closing this PR since better resolution had been found and placed under review in ocl: https://github.com/Open-CAS/open-cas-linux/pull/597
Problem: mdadm --zero-superblock command triggers udev and before calling next command it's needed to wait until this event ends. 
Resolution: Instead of using sleep command it's better/safer to call "udevadm settle" which would wait for event to be completed and then perform removing partitions.