Update device's path handling according to incoming changes in OCL
Open-CAS/test-framework pull request #219
Opened 2020-11-25 16:44 UTC by Ostrokrzew

2020-11-25 16:44 UTC, pep8speaks commented
Hello @Ostrokrzew! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`test_tools/disk_utils.py`](https://github.com/Open-CAS/test-framework/blob/0d5bc6f3d518dbd80c6ed9e4df65cea4dc57b313/test_tools/disk_utils.py):

> [Line 212:9](https://github.com/Open-CAS/test-framework/blob/0d5bc6f3d518dbd80c6ed9e4df65cea4dc57b313/test_tools/disk_utils.py#L212): [E123](https://duckduckgo.com/?q=pep8%20E123) closing bracket does not match indentation of opening bracket's line

2020-12-02 15:12 UTC, robertbaldyga requested changes

2020-12-02 15:12 UTC, robertbaldyga commented on storage_devices/raid.py
> +        raid = [r for r in Mdadm.examine_result() if r["path"] == get_by_id_link(raid_link)][0]
It doesn't look correct. It seem that `Mdadm.examine_result()` returns readlinked paths, not by-id symlinks.

2020-12-02 15:12 UTC, robertbaldyga commented on test_tools/fs_utils.py
> +    raise ValueError(f'By-id device link not found for {path}')
It doesn't seem to be necessary. We can just require disk paths in config to be by-id links.

2020-12-02 15:12 UTC, robertbaldyga commented on test_tools/mdadm.py
> +            details[key]["path"] = get_by_id_link(key)
It doesn't seem right. Will it work with symlink? I guess this readlink was there for a reason.

2020-12-03 14:27 UTC, Ostrokrzew commented on storage_devices/raid.py
> +        raid = [r for r in Mdadm.examine_result() if r["path"] == get_by_id_link(raid_link)][0]
right

2020-12-03 14:32 UTC, Ostrokrzew commented on test_tools/fs_utils.py
> +    raise ValueError(f'By-id device link not found for {path}')
OK, I renamed this function and modify it to only validate input (from config or disk finder).

2020-12-03 14:32 UTC, Ostrokrzew commented on test_tools/mdadm.py
> +            details[key]["path"] = get_by_id_link(key)
You're right.

2020-12-04 13:18 UTC, Ostrokrzew commented on test_tools/fs_utils.py
> +    raise ValueError(f'By-id device link not found for {path}')
After some investigation I realized that we need function like this for internal purposes, so I created another function. User's input is now validated, so it must be proper. Only automated creation of objects of type `Device` (and derived) uses new function named `resolve_to_by_id_link`. If I'm wrong, please tell me.

2020-12-22 08:45 UTC, katlapinka approved these changes

2020-12-22 09:25 UTC, robertbaldyga requested changes

2020-12-22 09:25 UTC, robertbaldyga commented on storage_devices/disk.py
>          self.device_name = path.split('/')[-1]
Assuming path is always `/dev/by-id` this will not work. Please use `get_device_id()` wherever `device_name` is needed.

2020-12-22 09:25 UTC, robertbaldyga commented on test_tools/fs_utils.py
> +    path = os.path.abspath(path)
Why don't we just expect path to be absolute and raise an exception if `os.path.isabs()` returns `false`? That way we could drop return value from this function, which anyway seems unnatural for a function that is meant to just check path correctness.

2020-12-22 09:25 UTC, robertbaldyga commented on storage_devices/disk.py
> +                self.system_path = fs_utils.validate_dev_path(self.device_name)
1. This is vulnerable to path change during reboot.
2. It could be easily replaced with `realpath(self.path)` wherever it's needed.

2020-12-22 13:17 UTC, katlapinka approved these changes

2020-12-22 14:13 UTC, mmichal10 approved these changes

2020-12-22 14:20 UTC, robertbaldyga approved these changes

2020-12-22 14:20 UTC, merged