Add increment offset to fio params
Open-CAS/test-framework pull request #221
Opened 2020-11-26 06:55 UTC by katlapinka

Signed-off-by: Katarzyna Lapinska <katarzyna.lapinska@intel.com>

2020-11-26 10:36 UTC, Ostrokrzew submitted a review, later dismissed

2020-11-26 10:36 UTC, Ostrokrzew commented on test_tools/fio/fio_param.py
> +    def offset_increment(self, value: str):
I know the type is only a suggestion in Python, but I think You could put here 'int' instead of 'str', like fio's manual shows.

2020-11-26 10:50 UTC, katlapinka commented on test_tools/fio/fio_param.py
> +    def offset_increment(self, value: str):
this parameter can be used also with string value, e.g. "50M"

2020-11-26 10:53 UTC, Ostrokrzew commented on test_tools/fio/fio_param.py
> +    def offset_increment(self, value: str):
You're right, my fault, didn't check manual well.

2020-11-27 08:24 UTC, robertbaldyga requested changes

2020-11-27 08:24 UTC, robertbaldyga commented on test_tools/fio/fio_param.py
> +    def offset_increment(self, value: str):
Binary prefix units (e.g "50MiB") are also supported, so maybe we want to use `Size` instead?

2020-11-27 16:55 UTC, Ostrokrzew approved these changes

2020-11-30 08:50 UTC, Ostrokrzew approved these changes

2020-12-02 10:08 UTC, robertbaldyga approved these changes

2020-12-02 10:08 UTC, merged