Fix disk finder
Open-CAS/test-framework pull request #229
Opened 2021-01-12 09:05 UTC by Ostrokrzew

Fix `disk_finder` according to recent changes in receiving paths.
Add functionality in `fs_utils` to create symbolic links as suggested.

2021-01-25 07:52 UTC, katlapinka commented on test_tools/fs_utils.py
> +
I wonder if it wouldn't be better to place this method as a static method in Symlink class

2021-01-25 16:50 UTC, Ostrokrzew commented on test_tools/fs_utils.py
> +
I thought about it before and I wasn't entirely convinced, but now I am.

2021-03-04 13:04 UTC, Deixx requested changes

2021-03-04 13:04 UTC, Deixx commented on test_utils/filesystem/symlink.py
> +        TestRun.executor.run(f"ln -s {target} {full_path} {'-f' if force else ''}")
We need a successful execution to return Symlink, so:
```suggestion
        TestRun.executor.run_expect_success(f"ln -s {target} {full_path} {'-f' if force else ''}")
```

2021-06-14 07:57 UTC, Deixx approved these changes

2021-08-09 08:54 UTC, karolinavelkaja approved these changes

2021-08-09 10:58 UTC, rafalste approved these changes

2021-08-12 13:33 UTC, robertbaldyga requested changes

2021-08-12 13:33 UTC, robertbaldyga commented on test_utils/filesystem/symlink.py
> +    def get_symlink(link_path, target, **params):
This function essentially does not just "get" symlink. It creates it or returns existing one if present - behavior very similar to O_CREAT flag. Please rename it to `create_symlink()`.

2021-08-12 13:33 UTC, robertbaldyga commented on test_utils/filesystem/symlink.py
> +                create_directory(parent_dir, True)
Why does this function create a directory? It doesn't seem to be what user would expect from a function operating on symlinks.

2021-08-13 11:35 UTC, karolinavelkaja commented on test_utils/filesystem/symlink.py
> +                create_directory(parent_dir, True)
To create a symlink the specific directory must exist otherwise we get failure for link creation (No such file or directory). I think it's worth to take care of this here and I would stay with creating chosen directory.
Other solution would be to have 2 functions - one which can return failure in case of directory absence and second "don't worry, if you want this symlink I make sure you get it" like here.

2021-08-20 13:43 UTC, karolinavelkaja commented
Closing since Sławek is no longer in our team.
New review: https://github.com/Open-CAS/test-framework/pull/259

2021-08-20 13:43 UTC, closed without merging

2021-08-20 13:44 UTC, karolinavelkaja commented on test_utils/filesystem/symlink.py
> +                create_directory(parent_dir, True)
@robertbaldyga please respond/review in new PR: https://github.com/Open-CAS/test-framework/pull/259