Fixes due to the change with by-id devices paths
Open-CAS/test-framework pull request #230
Opened 2021-01-15 08:53 UTC by katlapinka

Signed-off-by: Katarzyna Lapinska <katarzyna.lapinska@intel.com>

2021-01-18 17:19 UTC, Ostrokrzew approved these changes
I assume You use these changes in tests so they work.

2021-01-25 16:29 UTC, Ostrokrzew requested changes

2021-01-26 09:08 UTC, Ostrokrzew approved these changes

2021-01-26 11:05 UTC, Deixx approved these changes

2021-01-26 11:06 UTC, merged

2021-01-26 15:56 UTC, mmichal10 approved these changes