LVM api
Open-CAS/test-framework pull request #234
Opened 2021-01-21 13:10 UTC by karolinavelkaja

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-01-21 13:10 UTC, pep8speaks commented
Hello @karolinavelkaja! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`storage_devices/lvm.py`](https://github.com/Open-CAS/test-framework/blob/84a97bc45a8f331a465f26609c04e8ebc912629d/storage_devices/lvm.py):

> [Line 68:20](https://github.com/Open-CAS/test-framework/blob/84a97bc45a8f331a465f26609c04e8ebc912629d/storage_devices/lvm.py#L68): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 141:1](https://github.com/Open-CAS/test-framework/blob/84a97bc45a8f331a465f26609c04e8ebc912629d/storage_devices/lvm.py#L141): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-01-22 14:01 UTC, katlapinka submitted a review, later dismissed

2021-02-04 14:57 UTC, karolinavelkaja commented on test_tools/volumes.py
> +#
Sure! I would just stay with name 'make_sure_lv_is_active()' because this method not just checks if lv is active but already takes care it will be (action assumed).

2021-02-04 15:41 UTC, karolinavelkaja commented on test_tools/volumes.py
> +            if "PV" in line:
Good point! This corresponds with old implementation but looks like the appropriate here is "VG" to check :)

2021-02-24 12:53 UTC, karolinavelkaja commented on test_tools/disk_utils.py
> -    return re.search(r"cas\d+-\d+", path) is not None
wrong merging, first return to be removed

2021-02-25 08:58 UTC, Ostrokrzew requested changes

2021-02-25 08:58 UTC, Ostrokrzew commented on test_tools/disk_utils.py
> +    if re.search(r"cas\d+-\d+", path) or re.search(r"/dev/dm-\d+", path) is not None:
Maybe create list of whitelisted paths, iterate through it and return True when match appears.

```python
 def _is_dev_path_whitelisted(path: str): 
    whitelisted_paths = [r"/dev/cas\d+-\d+", r"/dev/dm-\d+"]
    for whitelisted in whitelisted_paths:
        if re.search(whitelisted, path) is not None:
            return True
    return False
```

This is just an example of what I thought.

2021-02-25 10:32 UTC, Ostrokrzew requested changes

2021-02-25 10:32 UTC, Ostrokrzew commented on storage_devices/lvm.py
> +    devices_list = list(devices)
`splitlines()` already returns list, so you can just sort it. Maybe move `splitlines()` to line belowe instead of casting `devices` to list.

2021-03-09 14:35 UTC, Ostrokrzew approved these changes

2021-03-11 13:04 UTC, Ostrokrzew commented
I think it closes https://github.com/Open-CAS/test-framework/issues/148

2021-06-14 06:52 UTC, Deixx requested changes

2021-06-14 06:52 UTC, Deixx commented on test_tools/disk_utils.py
> +            return False
This for will return for the first checked value regardless of the result.
You could do:
```suggestion
    for whitelisted_path in whitelisted_paths:
        if re.search(whitelisted_path, path) is not None:
            return True
    return False
```

2021-06-14 07:49 UTC, Deixx requested changes

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +
remove empty line

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +        return paths if paths else []
splitlines() returns [] for empty stdout - no need to explicitly return [] if paths == []
```suggestion
        paths = TestRun.executor.run(cmd).stdout.splitlines()

        return paths
```

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +
remove one empty line

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +                        return
check every link in links
```suggestion
                        continue
```

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +            TestRun.LOGGER.error(f"Incorrect type of first argument (volume_size_or_percent).")
```suggestion
            TestRun.LOGGER.error(f"Incorrect type of the first argument (volume_size_or_percent).")
```

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +                continue
Is this 'if' ever true? In `get_all_volume_groups`, you always append a pv after you create `vol_groups[vg] = []`

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +            raise ValueError("VG name needed for VG remove operation.")
```suggestion
            raise ValueError("VG name needed for LV remove operation.")
```

2021-06-14 07:49 UTC, Deixx commented on storage_devices/lvm.py
> +        cmd = f"vgdisplay| grep 'VG Name' | awk '{{print $3}}'"
```suggestion
        cmd = f"vgdisplay | grep 'VG Name' | awk '{{print $3}}'"
```

2021-06-15 14:16 UTC, karolinavelkaja commented on storage_devices/lvm.py
> +
next function doesn't belong to VolumeGroup class so there is expectation for 2 blank lines between functions

2021-06-15 14:38 UTC, karolinavelkaja commented on storage_devices/lvm.py
> +                continue
correct, seems unnecessary 😬

2021-06-16 07:21 UTC, Deixx submitted a review, later dismissed

2021-06-28 08:09 UTC, Ostrokrzew requested changes
I can approve that but give me descriptive and meaningful commit messages.

2021-08-30 11:48 UTC, Deixx approved these changes

2021-09-10 21:45 UTC, robertbaldyga approved these changes

2021-09-10 21:46 UTC, merged