Adding functions for getting device io max size and hw io size.
Open-CAS/test-framework pull request #241
Opened 2021-03-03 16:40 UTC by karolinavelkaja

adding functions for getting device io max size and hw io size. Also returning Size() from property.

Signed-off-by: Karolina Rogowska <karolina.rogowska@intel.com>

2021-03-04 09:16 UTC, Ostrokrzew submitted a review, later dismissed

2021-03-04 12:29 UTC, Deixx requested changes

2021-03-04 12:29 UTC, Deixx commented on storage_devices/device.py
> +        return Size(int(TestRun.executor.run_expect_success(f"cat {path}").stdout), Unit.KiloByte)
Sysfs properties are not only sizes, you cannot do this for all of them

2021-03-04 12:30 UTC, Deixx commented on storage_devices/device.py
> +        return Size(int(TestRun.executor.run_expect_success(f"cat {path}").stdout), Unit.KiloByte)
Additionally those are more likely kibibytes not kilobytes

2021-03-04 13:19 UTC, karolinavelkaja commented on storage_devices/device.py
> +        return Size(int(TestRun.executor.run_expect_success(f"cat {path}").stdout), Unit.KiloByte)
Correct, will fix this! Thanks!

2021-03-08 10:50 UTC, Ostrokrzew requested changes

2021-03-08 10:50 UTC, Ostrokrzew commented on storage_devices/device.py
> +        return int(TestRun.executor.run_expect_success(f"cat {path}").stdout)
You cannot cast output to `int` here - not all sysfs properties are numbers.

2021-03-08 11:33 UTC, karolinavelkaja commented on storage_devices/device.py
> +        return int(TestRun.executor.run_expect_success(f"cat {path}").stdout)
Oh ok, I've checked the usages of all properties here and I thought that all were numbers but maybe some of them which I've got zeroed may be set to other values. Thank you, I will fix this! :)

2021-03-08 13:01 UTC, Ostrokrzew approved these changes

2021-06-14 06:39 UTC, Deixx approved these changes

2021-06-17 13:38 UTC, katlapinka approved these changes

2021-06-17 13:38 UTC, merged