Add output redirection path for run_in_background command in executor
Open-CAS/test-framework pull request #255
Opened 2021-08-13 11:47 UTC by katlapinka

Signed-off-by: klapinsk <katarzyna.lapinska@intel.com>

2021-08-13 15:26 UTC, Deixx approved these changes

2021-08-17 14:14 UTC, mmichal10 submitted a review, later dismissed

2021-08-17 14:42 UTC, robertbaldyga requested changes

2021-08-17 14:42 UTC, robertbaldyga commented on connection/base_executor.py
> +                          stderr_redirection_path="/dev/null"):
Maybe `*_redirect_path` for short?

2021-08-18 07:21 UTC, mmichal10 approved these changes

2021-08-18 07:23 UTC, robertbaldyga approved these changes

2021-08-18 07:23 UTC, merged