Add PCI address to Device object
Open-CAS/test-framework pull request #257
Opened 2021-08-18 13:08 UTC by oshchirs

Signed-off-by: Oleksandr Shchirskyi <oleksand.shchirskyi@intel.com>

2021-08-19 09:18 UTC, katlapinka requested changes

2021-08-19 09:18 UTC, katlapinka commented on storage_devices/device.py
> +        self.pci_address = get_pci_address(self.get_device_id())
I think this should be added to NvmeDisk class, because there are other devices which inherit from Device class and they do not have such property, i.e. Raid, ErrorDevice

2021-08-19 12:37 UTC, oshchirs commented on storage_devices/device.py
> +        self.pci_address = get_pci_address(self.get_device_id())
done

2021-08-23 12:23 UTC, katlapinka commented on storage_devices/disk.py
> +        self.pci_address = get_pci_address(self.get_device_id())
I wonder if it wouldn't be helpful to add __str__ method to this class, so this pci_address would be printed at the begining of log, where all disks are listed. (See __str__ method in Disk class)

2021-08-23 12:43 UTC, Deixx submitted a review, later dismissed

2021-08-24 15:01 UTC, oshchirs commented on storage_devices/disk.py
> +        self.pci_address = get_pci_address(self.get_device_id())
done

2021-08-25 07:52 UTC, katlapinka approved these changes

2021-08-25 07:56 UTC, Deixx approved these changes

2021-08-25 09:32 UTC, merged