Add possibility to specify extra logs to dump
Open-CAS/test-framework pull request #258
Opened 2021-08-19 14:01 UTC by oshchirs

2021-08-20 07:54 UTC, katlapinka submitted a review, later dismissed

2021-08-20 13:33 UTC, robertbaldyga requested changes

2021-08-20 13:33 UTC, robertbaldyga commented on log/logger.py
> +            log_files.update(TestRun.usr.logs_to_dump)
test-framework should never access `TestRun.usr`. This is private field reserved for TF user. Please use `dut_config` instead to pass list of paths. (You can see how plugin configuration is handled. The list of logs may be specified in `conftest.py` before `TestRun.prepare()` is called).

2021-08-20 16:36 UTC, pep8speaks commented
Hello @oshchirs! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`core/test_run_utils.py`](https://github.com/Open-CAS/test-framework/blob/f99492c4d0b2fa014ff0644849d263495012251e/core/test_run_utils.py):

> [Line 73:1](https://github.com/Open-CAS/test-framework/blob/f99492c4d0b2fa014ff0644849d263495012251e/core/test_run_utils.py#L73): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-08-20 16:37 UTC, oshchirs commented on log/logger.py
> +            log_files.update(TestRun.usr.logs_to_dump)
done

2021-08-23 12:40 UTC, Deixx approved these changes
I'm wondering if we should make a distinction between logs, which can be easily copied from a platform (i.e. `/var/log/messages`) and those that require dumping a command output first (i.e. `dmesg`, `cat /proc/mdstat`).
Sth like:
```
logs = { "messages": "/var/log/messages",
         "dmesg": "dmesg"
         "mdstat": "cat /proc/mdstat"
}

for log_name, log_source_path in log_files.items():
    if not file_exists(log_source_path):    # will not exist for "command logs"
        executor.run(f"{log_source_path} > /tmp/{log_name})
        log_source_path = "/tmp/" + log_name
    ...
    executor.rsync_from(log_source_path, log_destination_path)
```

2021-08-24 09:17 UTC, katlapinka approved these changes

2021-08-24 14:25 UTC, robertbaldyga approved these changes

2021-08-24 14:26 UTC, merged

2021-08-24 14:33 UTC, robertbaldyga commented
> I'm wondering if we should make a distinction between logs, which can be easily copied from a platform (i.e. `/var/log/messages`) and those that require dumping a command output first (i.e. `dmesg`, `cat /proc/mdstat`).
> Sth like:
> 
> ```
> logs = { "messages": "/var/log/messages",
>          "dmesg": "dmesg"
>          "mdstat": "cat /proc/mdstat"
> }
> 
> for log_name, log_source_path in log_files.items():
>     if not file_exists(log_source_path):    # will not exist for "command logs"
>         executor.run(f"{log_source_path} > /tmp/{log_name})
>         log_source_path = "/tmp/" + log_name
>     ...
>     executor.rsync_from(log_source_path, log_destination_path)
> ```

This looks a bit fragile. We could make full-fledged API for that instead. Something like
```python
TestRun.attach_log(log_path, target_name=None, dump_fn=None)
```
where `dump_fn` would be a function that dumps the actual log to a file. That way we can even have logs that require more sophisticated extraction method, or logs that are filtered or preprocessed in some other way.